### ISSUE TITLE
ERA failing to detonate with advanced vehicle damage.

### ISSUE THREAD

**Issue by realchud** [acemod/ACE3#10315]
**Mods:**
Only CBA and ACE

**Description:**
With the advanced vehicle damage setting turned on, ERA on all tanks fails to detonate, no matter what it is hit with.
With the setting turned off, ERA detonates as it should.

**Steps to reproduce:**

1. Turn on advanced vehicle damage.
2. Spawn tank with ERA panels
3. Shoot an RPG at said ERA panels
4. Observe effects

**Expected behavior:**
The ERA is supposed to explode.

**Where did the issue occur?**
Singleplayer Editor.

**Log Files:**
- https://pastebin.com/vLvw4FpG

**Additional context:**
None

**Screenshots:**
![image](https://github.com/user-attachments/assets/3cffa79e-ef41-49fd-a0ac-3f9b9e1c848a)

**Comment by realchud** [comment]
![image](https://github.com/user-attachments/assets/18b176d2-e6c9-4e47-bec3-a267c8faa66e)
RHS vehicles appear to have their ERA working fine however.

**Comment by johnb432** [comment]
Can you try with the current master branch? Either by building it yourself or using https://steamcommunity.com/sharedfiles/filedetails/?id=1882627645.
The reason why I'm asking is because I'm fairly certain this has already been fixed in master.

**Comment by realchud** [comment]
Will it save all my ACE settings? Or can I just import the old settings and it will work.
Anyways, I'll try it and report back.

**Comment by johnb432** [comment]
> Will it save all my ACE settings? Or can I just import the old settings and it will work. Anyways, I'll try it and report back.

The values of the settings you have set won't be affected by mod version changes.

**Comment by realchud** [comment]
Still not working
I'm pretty sure the only vehicles that got fixed semi recently were the RHS vehicles
Vanilla vehicles are still broked

**Comment by johnb432** [comment]
> I'm pretty sure the only vehicles that got fixed semi recently were the RHS vehicles

#10168 (and  #10169 to a degree) - it was broken for all vehicles that didn't use lowercase hitpoint names. RHS vehicles had their ERA updated to include ones that RHS added at some point.

>Vanilla vehicles are still broked

Works just fine for me. I tested it on the exact same panel as you shot at and that one and the one to the right of it were both destroyed.

Can you upload your RPT log of the test mission that you do with `Anrop ACE3 Master` and send the Advanced Vehicle Damage CBA settings? You need to also give the weapon, magazine and vehicle you are using to test, so I can properly try to replicate said behaviour.

**Comment by SnagleTooth** [comment]
RHS AP rounds don't trigger ERA like they are supposed to. Vanilla AP rounds seem to work fine.

(vid of M829A3 AP round from a RHS M1A1 failing to trigger the ERA on a T-90SM)
https://github.com/user-attachments/assets/f2277ec0-bdb2-40cb-a1e8-6f38cdb41505

**Comment by johnb432** [comment]
It seems the RHS M829 rounds act in a manner not properly compatible with advanced vehicle damage.

**Comment by SnagleTooth** [comment]
Seems that this bug has been fixed in the latest update.
