### ISSUE TITLE
Interaction menu flies off the screen diagonally

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#1474]
ACE 3 launches however the interactions are broken. (self and object).  I don't know how to run (clipi)
or dlls with command line and would not know what to write to it if I did. 
 The interaction target(DOT) shows on screen (red) and the cursor appears, all for a split second,  then fly off the screen diagonally bottom right to top left. U can make out the text for a split second as well, but its not usable. The debug tool also is beyond my expertise,  but isw available at the Stratus TEST map for ACE.  MayB someone could tell me how I could debug it with the available tools.  I ran this on two separate computers, neither have Interaction.  While AGM interaction works fine..! This should be a 
popular approach since the two modifications are so similar.?!    dave  (dvd.brewster@yahoo.com)
  MayB I even have team viewer

**Comment by dvdbrewster** [comment]
CBA is running.  other ACE 3 features are working.  Tried on ACE # test map Stratus. So module is 
present.

**Comment by esteldunedain** [comment]
Hi, thanks for the report. tbh I'm not sure how we can debug this, cause it's incredibly weird. Let me think about it a little moreand I'll get back to you. In the mean time, two things would be very usefull:

* A video, or at least a few screenshots in quick succession showing the issue
* The RPT log that Arma prints of a session in which the error occurs. They are located on the following path: `C:\Users\YourUserNameHere\AppData\Local\Arma 3\`. Upload the lastest one somewhere and give as the link.

**Comment by dvdbrewster** [comment]
OK

**Comment by dvdbrewster** [comment]
I don't have a DROP BOX

**Comment by dvdbrewster** [comment]
see  how the icons float off the screen,  
![object interactions 7](https://cloud.githubusercontent.com/assets/11699529/7944477/bd5e8b80-091f-11e5-9d53-06a0ad93dbb9.jpg)
![object interactions 2](https://cloud.githubusercontent.com/assets/11699529/7944479/bfe519f0-091f-11e5-8a32-08666d6a743e.jpg)
![object interactions 3](https://cloud.githubusercontent.com/assets/11699529/7944481/c1e41454-091f-11e5-8a73-57c890293fb7.jpg)
![object interactions 6](https://cloud.githubusercontent.com/assets/11699529/7944485/c49ccd44-091f-11e5-809f-3691a3743c45.jpg)
![object interactions](https://cloud.githubusercontent.com/assets/11699529/7944487/c6bc3844-091f-11e5-8e2a-951c4f596972.jpg)
![self interactions 5](https://cloud.githubusercontent.com/assets/11699529/7944489/cad9d22e-091f-11e5-8f25-ea6972e77266.jpg)
![self interaction 2](https://cloud.githubusercontent.com/assets/11699529/7944494/d009847e-091f-11e5-9cc8-0f37e0864cfd.jpg)
![self interaction 3](https://cloud.githubusercontent.com/assets/11699529/7944497/d1b08926-091f-11e5-8b85-594ece091a63.jpg)
![self interaction 4](https://cloud.githubusercontent.com/assets/11699529/7944502/d32c82dc-091f-11e5-937b-939800a77da4.jpg)
![self interaction](https://cloud.githubusercontent.com/assets/11699529/7944503/d4b7b46e-091f-11e5-999b-9f0a414f1c96.jpg)
![self interactions 6](https://cloud.githubusercontent.com/assets/11699529/7944504/d6c8b3e8-091f-11e5-9576-673c9f8cd349.jpg)

If u email me I will email the rpt back to you..

**Comment by esteldunedain** [comment]
Thanks, mail sent

**Comment by esteldunedain** [comment]
RPT sent by mail:

https://gist.github.com/esteldunedain/53487ed7353851500f9e

@dvdbrewster, tbh I can't find anything wrong there. Let me test if I can repro this myself tomorrow.

**Comment by dvdbrewster** [comment]
ok.

**Comment by Cathlamet** [comment]
I haven't witnessed this particular phenomenon, but we have found that many ACE3 interactions are compromised by the latest CBA updates.  Does a CBA downgrade to 1.1.20.xxx seems to iron it all out for ya too?

**Comment by ViperMaul** [comment]
All ACE3 self-interaction problems should be fixed by the latest RC7 Hotfix 1.1.22.xxx

**Comment by Cathlamet** [comment]
Didn't seem to be the case in my testing earlier today but will revisit ASAP.  Thanks Viper!

**Comment by Cathlamet** [comment]
Just a heads-up Viper, while we never had too much issue with the self-interactions to begin with, AI interactions and vehicle interactions (non-local?) appear still absent with CBA 1.1.22.150602 (PWS).

**Comment by dvdbrewster** [comment]
I just tried the interactions again. It still does not  work.  (cba update).

**Comment by ViperMaul** [comment]
@dvdbrewster 
Our goal is to share the same experience that you have. Reproduce the same bug. In order to do this we need to use the exact same units and sometimes the exact same mod you are using. This is why the RPT is very important. 

From your RPT however, I cannot tell the exact unit or class name you use for the helo or unit that is experiencing broken self-interactions. 

To help this, perhaps you can answer the question or send the mission.sqm or pbo to @esteldunedain. This will help make a speedy diagnosis and figure out if the problem is in ACE or CBA or both.

**Comment by ViperMaul** [comment]
After a closer review of your RPT and the screenshots provided it appears that you are using the B_Soldier_F class unit and are standing and attempting to interact with the Ghost Hawk. 

So far I cannot reproduce the problem. So I am guessing my ACE Options are different from yours. We could really use a screenshot of your current ACE Options with respect to your interaction settings.

**Comment by dvdbrewster** [comment]
I tried resseting options. Then arranging some different cfgurations.  It doesn't seem to change for me.
Missions (2) were end game and ACE test mission. various roles. The caching of mission pbos has discontinued(cba?) I read something about cache disabling.. (new) I haven't had a minute or two to defeat it,  lol.   Im sending two rpts from the two missions.and Ill screenshot  my settings.

**Comment by dvdbrewster** [comment]
settings
![settings](https://cloud.githubusercontent.com/assets/11699529/7966378/901e3580-09d8-11e5-81f7-624e3827aeb7.JPG)
![settings 2](https://cloud.githubusercontent.com/assets/11699529/7966382/91b236bc-09d8-11e5-93ef-651e5664b03a.JPG)
![flys off screen](https://cloud.githubusercontent.com/assets/11699529/7966383/940a3914-09d8-11e5-8f16-17f462a01e20.JPG)

**Comment by dvdbrewster** [comment]
rpts

**Comment by dvdbrewster** [comment]
U got them?  (on github a few minutes ago.)

**Comment by Pelaez14** [comment]
I have an issue, when trying to open the ace 3 menu it doesnt appear, it only shows the red circle but no actions are shown, also i would like to know when is this mod going to be updated
Thank you

**Comment by ViperMaul** [comment]
@Pelaez14,
You really need to create your own proper issue ticket. 
https://github.com/acemod/ACE3/issues/new

**Comment by Pelaez14** [comment]
Ok i just did

**Comment by dvdbrewster** [comment]
MayB I can copy your recommended settings. ( reset doesn't help)  And why does AGM work and ACE 3  does not ?

**Comment by esteldunedain** [comment]
@dvdbrewster,

try setting `Keep cursor centered` to `No`

btw, do you have a three monitor setup or something like that?

**Comment by esteldunedain** [comment]
@PabstMirror, after seeing the settings I'm pretty sure this has to be related to `Keep cursor centered`; do you imagine any reason why it could break?

**Comment by dvdbrewster** [comment]
No I see it working usually. I'll try using NO.  I have single monitor 2 vid cards ( sli )

**Comment by dvdbrewster** [comment]
I changed the setting, and Interaction becomes usable. !  Still U have to be relativeley in a position to the vehicle to interact without the menu  being off the screen. (resolution 1920x1080 16x9)
If u stand in the very (vERY) wrong spot to interact, the additional dialogues (choices)  are out of the screen still. And interaction seem to initiate in different areas of the display(screen) when U are in a different position relative to the vehice, ( in back, or to the side..) !      Also I notice that pressing to interact  the Menu doesn’t toggle onto the screen, U must Hold Press.    THANKS .

**Comment by esteldunedain** [comment]
> Still U have to be relativeley in a position to the vehicle to interact without the menu  being off the screen. If u stand in the very (vERY) wrong spot to interact, the additional dialogues (choices)  are out of the screen still

That's because you have "Interaction  text size" set to "Very Big", which is not really usable without `Keep cursor centered` working. Select "Normal" for a better experience.

>  Also I notice that pressing to interact  the Menu doesn’t toggle onto the screen, U must Hold Press.    

That's by design

**Comment by dvdbrewster** [comment]
thanks again       .00.

**Comment by dvdbrewster** [comment]
Say since I was so cooperative in waiting for u to tell me this simple fix,   Tell me what the pbo for optionalserver is and how I use it with the included user cfg,  I rent a JestSerbers arma 3  max perf ai. and I like to start it sometime with ace.?

**Comment by dvdbrewster** [comment]
I just tried 3 missions on multiplayer.  The rpt here indicates the three titles.  I can use self interact on all three. But the only mission which has interaction with anything else is ACE test map startus.  The other 2 are not showing menu on interaction. If use “no cursor on interaction” I can geta red circle, no menu. If set “ use cursor on interaction) there is no red circle, but the cursor is there with no menu. It makes no difference if “use lists for interaction menus” is on or off.

**Comment by dvdbrewster** [comment]
heres the screenshots . The ones with nothing in them are the interact object ones. The red circle is with the cursor turned off.
![2015-06-04_00011](https://cloud.githubusercontent.com/assets/11699529/7998787/253324b4-0af6-11e5-8fc6-4892a87db440.jpg)
![2015-06-04_00012](https://cloud.githubusercontent.com/assets/11699529/7998785/25318460-0af6-11e5-8020-c02b331cdc7a.jpg)
![2015-06-04_00014](https://cloud.githubusercontent.com/assets/11699529/7998786/2532dea0-0af6-11e5-9dfb-0f517dcc52e8.jpg)
![2015-06-04_00008](https://cloud.githubusercontent.com/assets/11699529/7998788/25342ad0-0af6-11e5-9cf1-2b64840280d0.jpg)
I emailed the rpt from playing multiplayer 3 missions.  SelfInteract works everywhere. Object Interact only worked on ACE test mission map.. stratus.  Other two were cti maps.(agm works there.) Proman
steam vers. and becti Annabelle 1.50.  realArmor. CBA and ACE 3 were the addons.

**Comment by dvdbrewster** [comment]
I guess Im working ok. CTI maps seem to have all the same trouble with some of the vehicles. ACE mp maps.. work fine.  Thx.
