### ISSUE TITLE
Goggles effect disappears when aiming as Gunner

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1721]
ACE3 Version: 3.1.1.1 Release and 3.1.2.0 ce0bbe60d39411398a26161225e0c50c977a61e0

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
* None

**Description:**
Goggles effect disappears in gunner  view making switching painful as it keeps changing the tint/brightness.

**Steps to reproduce:**
* Put on some Goggles (eh. Shades)
* Enter a vehicle as Gunner (eg. Offroad)
* Aim down the sights and see the effect disappear
* Look normally without aiming and see the effect reappear

**Where did the issue occur?**
Singleplayer - Editor
Multiplayer - Dedicated

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
I think the problem is ace_goggles_fnc_isGogglesVisible - line 25:

`if ((vehicle _unit) != _unit) exitWith {(cameraView != "GUNNER")};`

**Comment by CorruptedHeart** [comment]
This was done on purpose to avoid having goggle effects while using camera based weapons like on the Hunter.

I am unsure whether that is still something we want to consider, especially now that gear is accessible from within a vehicle so glasses can be removed. (I implemented this back when Arma didn't allow that).

**Comment by SilentSpike** [comment]
I'd side with removing it and letting players remove their own goggles before using camera based weapons.

**Comment by jonpas** [comment]
Agreed with @SilentSpike as it should happen in camera views as well. Effect probably wouldn't be the same, but you still see the tint when looking at a screen that has the image of the camera.

**Comment by esteldunedain** [comment]
In my opinion it's fine as is. Vanilla Arma does similar things already (like auto removing the personal NVG googles when scoping through vehicle optic)

**Comment by jonpas** [comment]
The point is it is extremely annoying and eye-bleeding seeing the effect change drastically each time you look down the sights on a technical for example.

Also, since when did vanilla become something we look up to! :grin:

**Comment by Tenga** [comment]
I'd agree with @esteldunedain that if the only choice is either having it on vehicle optics or not having it, is to keep the current setup. My reasoning being that it's much more cumbersome to fiddle with the Arma inventory than it is just to look over/through your glasses IRL (http://i.imgur.com/1XJh1B4.jpg).

Alternative solutions could be:

- Detect the optics model of the current view. If I remember correctly, "GUNNER" views where you are not actually looking through a viewfinder/screen usually have it defined as an empty string. If there is no optics model, apply the glasses effect, otherwise don't.

- A flag like ACE_opticIsViewfinder or something.

- Having the effects on by default for vehicle GUNNER and adding a keybind to "look over glasses". :stuck_out_tongue:

**Comment by jonpas** [comment]
> Detect the optics model of the current view. If I remember correctly, "GUNNER" views where you are not actually looking through a viewfinder/screen usually have it defined as an empty string. If there is no optics model, apply the glasses effect, otherwise don't.

That would be the most viable solution if what you say is true.
