### ISSUE TITLE
ACE3 - Zeus.

### ISSUE THREAD

**Issue by Blitzkreigery** [acemod/ACE3#1817]
**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
*None*

**Description:**
*ACE 3 is conflicting with Zeus, it says "[BIS_fnc_moduleExecute] Cannot execute module, error found in 'ace_zeus_fnc_bi_moduleCurator'".*

**Steps to reproduce:**
I used CBA and ACE3, placed down a zeus module and connected it to a player then hit previwe, and I was unable acess or use zeus.

**Where did the issue occur?**
*Singleplayer*

**RPT log file:**
*http://pastebin.com/YcN7m41G*

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Blitzkreigery** [comment]
it has been fixed.

**Comment by Blitzkreigery** [comment]
the ticket has been fixed not the problem.

**Comment by SilentSpike** [comment]
I haven't been able to reproduce this, but I feel like I've experienced a similar problem elsewhere in the past. Will keep an eye out for it.

**Comment by Astavinu** [comment]
i experience this issue on dedicated servers only. mission to reproduce: https://www.dropbox.com/s/tztr9991md3xozg/Zeus%2520test.Altis.pbo?dl=0

tested with the latest stable release and
mod=@CBA;@ACE --> Zeus not accessible on mission start + tremendous frame jitter in zeus interface
mod= --> Zeus accessible, no frame jitter

**Comment by SilentSpike** [comment]
Can I ask what ace_zeus settings you're using?

I suspect that this issue might already be fixed by 398f1c768f617768c9971608e6754ff8fef385fd

**Comment by Astavinu** [comment]
yeah, that commit looks promising. could you try to reproduce it with that commit? just observe (getAssignedCuratorLogic player) with given mission right after you spawned :)

**Comment by SilentSpike** [comment]
I can't reproduce the issue at all, which is why I suspect it's already been fixed :stuck_out_tongue_closed_eyes:

**Comment by narrowsoul** [comment]
Still have the issue on my server. I notice 397f1c7 was updated on the 21st of June, and the latest version I can find was released on June 17, any word on that?

**Comment by SilentSpike** [comment]
Well, the issue will still be there in the release build of course. Anyone is welcome to test the development build and confirm if it has been fixed. Unfortunately I can't do that since I was never able to reproduce it in the first place.

**Comment by Astavinu** [comment]
SilentSpike, you cannot reproduce that issue with 3.1.1 stable?

**Comment by SilentSpike** [comment]
@Astavinu I don't have a stable build set up currently :smile:

Usually I'd set one up to test but I've been pretty busy developing the spectator system over the last few weeks. However, I wasn't able to reproduce it in pre-3.1.1 builds (likely because I had never tested it after that error was introduced).

**Comment by SilentSpike** [comment]
I believe this is fixed in 3.2.0. If the problem persists then please open a new issue :+1:
