### ISSUE TITLE
cannot attach Laser Pointer (Green) [the one that emits visible light] to any rifle

### ISSUE THREAD

**Issue by rlorenr** [acemod/ACE3#2322]
ACE 3.2.1 (stable)[subscribed via steam workshop and automatically included and updated via steam default launcher]

**MODS:**
* @ace
* @CBA_A3  
tested with and without the following:
* @ASDG_JR
* @mrt_accfncs

**PLACED ACE3 MODULES**
* none

**DESCRIPTION**
i am unable to attach the green laser pointer from the ace 3 mod to any gun.

i was told that i needed to get asdg joint rails and mrt accessory functions as well. i downloaded and activated the newest version of both of them and again i still could not attach the laser pointer. i tried de-activating all of my other mods just in case there was a conflict somehow and still no joy; again testing with and without the asdg_jr and mrt_accfncs.

i can attach the original laser from BIS that ace modifies to be laser pointer (red), but although it makes noise when pressing the cycling visibility modes button it never actually cycles. which as i understand is WaI.

**STEPS TO REPRODUCE**
launch arma
acquire the ace3 Laser Pointer (Green)
trying to drag the laser pointer into the appropriate slot on the equipped rifle does not work. all slots red.

**OCCURS IN**
both single and multi-player

**Comment by PabstMirror** [comment]
Grab the newest CBA: https://github.com/CBATeam/CBA_A3/releases/latest
That includes ASDG_JR so you can delete that

Then in @ACE folder open the optional folder and copy "compat_asdg.pbo" to addons folder.

This will all be fixed in next release.

**Comment by rlorenr** [comment]
i already got rid of asdg_jr as i sincerely did not believe that it was necessary as i already knew and confirmed by re-reading that asdg had been folded into cba_a3. i have the newest cba. i tested and the issue persisted even with the newest version from your source.

however the addition of dragging the file(s, including the bisign,) did resolve the issue. thank you for your help.

**Comment by jonpas** [comment]
For some more explanation, since ASDG JR got integrated into CBA, the contents of the file you dragged are needed to be compatible. Next release of ACE3 will have that file integrated (so you won't have to drag it in anymore).
