### ISSUE TITLE
virtual arsenal guys have bad hitpoints

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2768]
ACE 3.3.2 and CBA 2.1.2

ISSUE: static weapon gunners don't take damage in chest and head. Tried with vanilla only and it works fine, problem caused by ACE 3. 

HOW TO:
1. No modules placed straight into the arsenal.
2. Spawn a vanilla static XM307 ( HIGH ) with a gunner.
3. Shooting the gunner in the torso or head will cause no damage.

Video of the issue and vanilla comparison:
https://youtu.be/VSkzW_L_adQ

NOTE: This happened to me about 2 months ago as well and I thought just RDS statics were broken but turns out it was not the case.

**Comment by captainblaffer** [comment]
Hey, sorry to chip in, but are you sure this also happens when not in the virtual arsenal? I've noticed myself some weird scripts being active there, making some units invincible.

**Comment by commy2** [comment]
Also note that the virtual arsenal guys have weird hitpoint names, so this behaviour might be different on normal units. (And it will be different in Arma v1.54)

**Comment by xJenny99x** [comment]
Yes, but in vanilla it does not occur.

**Comment by commy2** [comment]
So? Those guys have broken selections.  All this changes in the next Arma release anyway with the new soldier protection stuff, so there is no point in fixing these guys now.

**Comment by xJenny99x** [comment]
Right, that's rational. Just hoping it's fixed in the next update, because I care.



I kind of feel a negative vibe, so don't get me wrong, I'm not trying to be an asshole and tear on your hard work, I really respect your work for the whole community, just trying to report bugs and stuff  so you can further improve ACE 3. It's obviously hard to perfect things like this and I truly hope that your end goal is perfection.

Being annoying was never my goal.
I'm sorry if I've been a nuisance, just tell me if I am and I'll stop opening issues.

**Comment by commy2** [comment]
You are not annoying at all. BI with their random changes (and reverting them one patch later!) is. They implemented basically bugged hitpoint configs in preperation of the soldier protection update that come in a future version in the current version of the game. Hitpoints that have no selections in the models currently, because the configs where changed, but the models are still not updated. It is all a mess, but we can't do anything about it at the current state of the game. We have to wait for 1.54 and them to sort their shit out, so we can adjust everything acordingly. There is no point in trying to fix stuff now, when BI will break them again (evidently in the 1.53 dev branch).

**Comment by Armilio** [comment]
Me too i have seen this bug. I solved it removing the vest to the gunner. With the vest you can see the bullets bouncing. So it's a issue with the vest, i don't know why, but i'm pretty sure. And it's not a problem with the 1.54 dev version: i have experienced this issue with the 1.52 stable version of the game.

**Comment by Neefay** [comment]
This is an extremely prevalent issue and I feel that the current label downplays the severity of this problem which is not at all only related to the Virtual Arsenal units, and basically makes gunners in mortars impossible to kill.

**Comment by SilentSpike** [comment]
Posted 17 days ago:
>All this changes in the next Arma release anyway with the new soldier protection stuff, so there is no point in fixing these guys now.
