### ISSUE TITLE
Player does not see that he's bleeding, no exist visual effect (red halo)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4214]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0.160713 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When a player is injured and is bleeding, but cannot heal himself, he does not see that he's bleeding. Now a red halo is not exist. This problem appeared in the last updates (1-2 updates last). 

**Steps to reproduce:**
Get the heavy wound and do not heal them. look at the lack of the visual effect durring of bleeding. Sometimes it appears, but in most cases this is not exist. Player can see only pain visual effect.

**Where did the issue occur?**
Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- ACE module Medical, ACE module Advanced Medical

**RPT log file:**

---

**Comment by DLEGION** [comment]
.....an what about bloodstains ? love vanilla ones...you can follow tracks in that way!
but in ACE....no bloodstains :(

**Comment by bux578** [comment]
@DLEGION please, don't hijack issues

**Comment by Glowbal** [comment]
> When a player is injured and is bleeding, but cannot heal himself,

When does this occure? Could you clarify? Bleeding should always be treatable, provided you have the bandages available.

**Comment by ZeusWrath** [comment]
> When does this occure? Could you clarify? Bleeding should always be treatable, provided you have the bandages available.
Hi.  I mean, if durring this moment you  no have medications or bandages for examples. 
Or if the wound reopens again and again. (Advanced Medicine)  In these cases the medical  menu show, that the player has a lot of bleeding, but there is no visual bleeding effect.  In previous versions of ACE3 it worked well.

**Comment by DLEGION** [comment]
sorry bux, didn mean to :(

**Comment by Glowbal** [comment]
Thanks @ZeusWrath. I think this should be fixed for 3.7.0.

**Comment by commy2** [comment]
Is it fixed? If so we should label and close this ticket.

**Comment by Glowbal** [comment]
We will need to confirm whatever or not this is still an issue.

**Comment by legman** [comment]
I can confirm this is still an issue with v3.9.2 + v3.10.  The bleeding effect is not visible on the screen, you have no idea you are bleeding which is quite troublesome with reopening wounds enabled.

I am having a hard time working out what could be causing it but what I can say is, when its not working, everyone in the server is affected. Could this be pointing at the medical sync?

**Comment by blackvenom2** [comment]
can confirm this bug.

**Comment by BaerMitUmlaut** [comment]
Medical rewrite is in, if this occurs again make a new issue please.
