### ISSUE TITLE
Vehicleammo cooking off when it's not supposed to!

### ISSUE THREAD

**Issue by Retch44** [acemod/ACE3#4602]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.0.0` (I can only asume from BI-Sign file name)
**ACE3 Version:** `3.7.0.6` (")

**Mods:**
- `@CBA_A3`
- `@ACE3 `
- `@RHS`
- `@other that wont interflict `

**Description:**
- Dealing critical damage to certain vehicle parts will cause the vehicleammo to start cooking off,
   I asume this happens as the commander turrets are counted as normal turrets.

**Steps to reproduce:**
- Place a vic with a commander turret, shoot the commander turret.

**Where did the issue occur?**
- Dedicated Server

**Video:**
http://plays.tv/video/5811804c36676267d3/thecourier-in-crewman-training?from=user
http://plays.tv/video/58112ba3d9cf42f93f/ty-ace-3?from=user

**Comment by Retch44** [comment]
Can't provide any further Intel, watch the videos or try for youself.

**Comment by jonpas** [comment]
Please update to latest CBA and ACE3 and try to reproduce. 

> @other that wont interflict

We'll decide that. Also please upload RPT.

**Comment by commy2** [comment]
Needs RPT file

**Comment by commy2** [comment]
I'll make this short and close it. This bug is fixed in the latest version. Please update your mods.

**Comment by Retch44** [comment]
Just saying I updated to latest version, still exsists, I see what I can do about getting you some prove...

**Comment by GIJed92** [comment]
not fixed

**Comment by GIJed92** [comment]
This bug is not fixed in the latest version. Please Fix your mods.

**Comment by jones140** [comment]
tested with latest ace and cba still happening video soon
http://pastebin.com/TXK6XsKL

**Comment by jones140** [comment]
https://www.youtube.com/watch?v=EFiEJBECyDA&feature=youtu.be

**Comment by commy2** [comment]
upload RPT please

**Comment by Retch44** [comment]
Check the Pastebin links: 
http://pastebin.com/QkEqnZhc

**Comment by jones140** [comment]
did you see this http://pastebin.com/TXK6XsKL

**Comment by GIJed92** [comment]
http://plays.tv/video/58123ff782197e6f3e/ace-no-need-for-at

**Comment by commy2** [comment]
Thanks

**Comment by Retch44** [comment]
1: https://gyazo.com/008756b0c3017bb64280d836438b5db6
2: https://gyazo.com/4f64f6713407960e0b246b0c66eb893d

This should be my last comment.
Good evening

**Comment by commy2** [comment]
Jeez. Stop with the videos.

**Comment by Glowbal** [comment]
Should be fixed by #4604
