### ISSUE TITLE
Outdated PBO error

### ISSUE THREAD

**Issue by BlueNexus** [acemod/ACE3#5169]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `Unknown` (stable)
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- ALiVE
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
When I try and play a scenario, I get an error stating that "File ace_compat_rhs_usf3.pbo is outdated", and the mission immediately ends. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
Attempt to play a scenario in singleplayer, or observe.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Singleplayer/Editor(singleplayer)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
None

**Comment by commy2** [comment]
You're supposed to fill out the template.

**Comment by bux** [comment]
@commy2 he kinda did
left the texts in there though

**Comment by BlueNexus** [comment]
I wasn't quite able to answer all of the questions.

**Comment by PabstMirror** [comment]
>File ace_compat_rhs_usf3.pbo is outdated

Means that arma is loading an old version of ace_compat_rhs_usf3.pbo from somewhere.

- I believe six updater might have had a delay between base game and the compats, but it should be fixed by now.
 - Steam should be fine
- Otherwise just search for `ace_compat_rhs_usf3.pbo` and replace it with the most recent version from `@ace/optionals`

**Comment by PabstMirror** [comment]
Is this still an issue for you?
I believe there should be official ACE 3.9.2 compats uploaded to six

Also #5177 should prevent this from happening on future releases

**Comment by BlueNexus** [comment]
No longer an issue, for me.

**Comment by dthchm** [comment]
nope, the problem is still on, for me at least. i tried about 6 different "compat_rhs" versions (if not more), tried with older/newer scenarios, updated ace (install/uninstall, manually from the site and through steam), and still. its not good.
but
when i turn off anything related to ace, its ok. sooo, any more ideas, could you guys share, please?

**Comment by PabstMirror** [comment]
unsubscribe from all ace on steam workshop, and delete all ace folders in your arma folder
then only subscribe to mod's directly from us here: https://steamcommunity.com/id/acemod/myworkshopfiles/?appid=107410

**Comment by dthchm** [comment]
Thank You!
It seems to be working now.
👍 
have a good day, all!
