### ISSUE TITLE
ACE3 - RHS compatibility mods falsely displayed as optional mods

### ISSUE THREAD

**Issue by Marcel1802** [acemod/ACE3#7753]
- **Arma 3:** `1.98.146373 [stable] (current / newest version)`
- **CBA:** `3.15.1 [stable] (current / newest version)`
- **ACE3:** `3.13.2 [stable] (current / newest version)`

**Description:**

If only the ACE 3 mod is running on the server and you subscribed the [RHS mods](https://steamcommunity.com/id/rhsmods/myworkshopfiles/?appid=107410) and the 'ACE 3 - RHS compatibility mods' ([for RHS:USAF](https://steamcommunity.com/sharedfiles/filedetails/?id=773125288), [for RHS:AFRF](https://steamcommunity.com/sharedfiles/filedetails/?id=773131200) & [for RHS:GREF](https://steamcommunity.com/sharedfiles/filedetails/?id=884966711)), the compatibility mods are displayed as optional mods falsely.

**Steps to reproduce:**

- subscribe to ACE3, the RHS Mods (RHS:USAF, RHS;AFRF, RHS:GREF & RHS:SAF), and, most importantly, the compatibility mods
- put ACE3 on the server
- do **not** put RHS & and the, if RHS is installed, required compatibility mods on the server

**Expected behavior:**

The compatibily mods should not be displayed on the 'optional mods' list because RHS is not installed on the server

**Where did the issue occur?**

The problem occures in the ArmA 3 launcher where the required & optional mods are displayed when you want to join a server

![github1](https://user-images.githubusercontent.com/13586726/84388267-90ec5a00-abf4-11ea-87fb-926b5ae22e40.PNG)
![github2](https://user-images.githubusercontent.com/13586726/84388271-92b61d80-abf4-11ea-8651-560b7ad990b3.PNG)

**Possible fix**
Sign the three compatibility mods (add bikeys)

**Comment by Vdauphin** [comment]
fixed by https://github.com/acemod/ACE3/pull/7859

**Comment by PabstMirror** [comment]
nothing was actively done to fix this

the optionals are signed (have a `.bisign` for the pbo) 
but there is no `keys` folder so maybe the problem is launcher needs to see the `.bikey`

**Comment by Vdauphin** [comment]
Well, strange, I checked again and the bug disappear
May be it is because I unfollow the ACE Compat RHS

My bad :)

**Comment by AkuSiansi** [comment]
Does the Issue still persists? Or is there a fix im not aware of / did not found yet?

I'm encountering the same problem on my server. RHS and related keys are not installed.

![sampel](https://user-images.githubusercontent.com/73439966/97114987-2ac02980-16f4-11eb-9e7f-0c659a321374.PNG)

**Comment by Marcel1802** [comment]
> Does the Issue still persists? Or is there a fix im not aware of / did not found yet?
> 
> I'm encountering the same problem on my server. RHS and related keys are not installed.

The problem still exists.
The addon files are signed but there is no bikey in the mod folder, so I guess they are signed with the same key ACE or RHS is signed with.

I think it will be fixed if you sign the compatibility mod with an own key (each of them).

**Comment by commy2** [comment]
Why does this matter? Who cares about the Arma Launcher?

**Comment by Marcel1802** [comment]
> Why does this matter? Who cares about the Arma Launcher?

People who don't know much about ArmA 3 mods use the launcher to join the server.
They will load the other mods, can't join and don't know what they did wrong.

**Comment by AkuSiansi** [comment]
The issuse is when you try to run a public server. Random players cant join it because they use the arma launcher and dont know better.

**Comment by HomelessMage** [comment]
In case anyone encounters this bug, this issue still persists.

**Comment by Mike-MF** [comment]
Solved by #9294
